INSERT INTO `keywords` VALUES ('C#', 1);
INSERT INTO `keywords` VALUES ('C++', 1);
INSERT INTO `keywords` VALUES ('C++ fpt', 2);
INSERT INTO `keywords` VALUES ('Fpt', 2);
INSERT INTO `keywords` VALUES ('Hsh', 1);
INSERT INTO `keywords` VALUES ('Mp3', 1);
INSERT INTO `keywords` VALUES ('Tài liệu fpt', 1);
INSERT INTO `keywords` VALUES ('ds', 1);
INSERT INTO `keywords` VALUES ('hau', 4);
INSERT INTO `keywords` VALUES ('hghghgv', 1);
INSERT INTO `keywords` VALUES ('java', 3);
INSERT INTO `keywords` VALUES ('jjjj', 1);
INSERT INTO `keywords` VALUES ('mp3', 2);
INSERT INTO `keywords` VALUES ('php', 16);
INSERT INTO `keywords` VALUES ('qưewqe', 2);
INSERT INTO `keywords` VALUES ('thinh', 1);
INSERT INTO `keywords` VALUES ('tài liệu', 1);
INSERT INTO `keywords` VALUES ('world', 1);
INSERT INTO `keywords` VALUES ('xin chào', 1);
INSERT INTO `keywords` VALUES ('ÂSA', 1);
INSERT INTO `keywords` VALUES ('đasadasd', 3);
INSERT INTO `keywords` VALUES ('đsđá', 1);
